import { createEnv } from '@t3-oss/env-nextjs'
import { z } from 'zod'

export const env = createEnv({
  server: {
    NODE_ENV: z.string().optional(),
    PAYLOAD_SECRET: z.string(),
    BETTER_AUTH_SECRET: z.string(),
    GOOGLE_CLIENT_ID: z.string(),
    GOOGLE_CLIENT_SECRET: z.string(),
    UPSTASH_REDIS_REST_URL: z.string(),
    UPSTASH_REDIS_REST_TOKEN: z.string(),
    PREVIEW_SECRET: z.string(),
    R2_BUCKET: z.string(),
    R2_ENDPOINT: z.string(),
    R2_REGION: z.string(),
    R2_ACCESS_KEY: z.string(),
    R2_SECRET_ACCESS_KEY: z.string(),
    DEVELOPMENT_MONGO_URI: z.string(),
    VERCEL_PROJECT_PRODUCTION_URL: z.string().optional(),
    PAYLOAD_PUBLIC_SERVER_URL: z.string().optional(),
    STRIPE_SECRET_KEY: z.string(),
    STRIPE_PUBLISHABLE_KEY: z.string(),
    STRIPE_WEBHOOK_SECRET: z.string(),
    AUTH_DB_URL: z.string(),
    AUTH_DB_TOKEN: z.string(),
    PAYMENTS_DB_URL: z.string(),
    PAYMENTS_DB_TOKEN: z.string(),
    SENDER_EMAIL: z.string(),
    SMTP_HOST: z.string(),
    SMTP_USER: z.string(),
    SMTP_PASS: z.string(),
    SMTP_PORT: z.coerce.number(),
  },
  client: {
    NEXT_PUBLIC_SERVER_URL: z.string().optional(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    PAYLOAD_SECRET: process.env.PAYLOAD_SECRET,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    PREVIEW_SECRET: process.env.PREVIEW_SECRET,
    R2_BUCKET: process.env.R2_BUCKET,
    R2_ENDPOINT: process.env.R2_ENDPOINT,
    R2_REGION: process.env.R2_REGION,
    R2_ACCESS_KEY: process.env.R2_ACCESS_KEY,
    R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
    AUTH_DB_URL: process.env.AUTH_DB_URL,
    AUTH_DB_TOKEN: process.env.AUTH_DB_TOKEN,
    PAYMENTS_DB_URL: process.env.PAYMENTS_DB_URL,
    PAYMENTS_DB_TOKEN: process.env.PAYMENTS_DB_TOKEN,
    DEVELOPMENT_MONGO_URI: process.env.DEVELOPMENT_MONGO_URI,
    VERCEL_PROJECT_PRODUCTION_URL: process.env.VERCEL_PROJECT_PRODUCTION_URL || '',
    NEXT_PUBLIC_SERVER_URL: process.env.NEXT_PUBLIC_SERVER_URL,
    PAYLOAD_PUBLIC_SERVER_URL: process.env.PAYLOAD_PUBLIC_SERVER_URL,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    SENDER_EMAIL: process.env.SENDER_EMAIL,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASS: process.env.SMTP_PASS,
    SMTP_PORT: process.env.SMTP_PORT,
  },
})
